### ISSUE TITLE
1.4.6 is a breaking change! "W10=" instead of "[]"

### ISSUE THREAD

**Issue by yvz5** [go-gorm/postgres#152]
Don't have time to create a playground link. its just too much work. updating 1.4.5 to 1.4.6 broke our system.

## Description
we have a table with a column of type `jsonb` in postgres. in go, we represent this column with `json.RawMessage` . in version 1.4.5 we can save an empty array into `jsonb` column and it would save `[]` in to the table. now, in the new version (1.4.6), it saves the value  `"W10="` instead of `[]` which can not be unmarshalled to a known object in go.

**Comment by maja42** [comment]
I implemented the `driver.Valuer` interface on a custom slice-type.
It produces `[]` for both nil-slices and empty slices (go best-practices state that they should be handled equivalently, so I serialize both variants to the same database value). Since 1.4.6, nil-slices are no longer converted to `[]`, but to `null`.

This took me a while to figure out. Luckily I had unit-tests that triggered not-null-constraint violations in my database.

**Comment by numaga94** [comment]
the same issue still presents in v1.4.7.

**Comment by maja42** [comment]
See also: https://github.com/jackc/pgx/issues/1566
