### ISSUE TITLE
Option to use a uri like „postgres://user:password@host:port/database“ 

### ISSUE THREAD

**Issue by Dattito** [go-gorm/postgres#70]
## Your Question
Simple Question, but hard to find an answer online: Is there an option to use URIs instead of DSNs to connect to the database? This would make working with Heroku Postgres a lot easier!

**Comment by jinzhu** [comment]
Maybe create an issue on pgx driver?

**Comment by ktarplee** [comment]
URI's already work with this driver in GORM since the underlying postgres driver already supports it.  I use URI all the time for gorm/postgres.   The only part that might not work is in this code base (but I have not hit an issue with it).  It is this line https://github.com/go-gorm/postgres/blob/6752fb0c81ab98d437cbb100026f72ea8444bd0f/postgres.go#L65

It would be nice if the documentation was updated to point out that URIs do in fact work.
